# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncci < Formula
  desc "neetoCI 1.0 command line interface."
  homepage "https://neetoci.com"
  version "1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0/ncci_Darwin_arm64.tar.gz"
      sha256 "a39a20c19c8ce5da8f07b882368a805a079ad95aaa08c8179d49e2f94b049eea"

      def install
        bin.install "ncci"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0/ncci_Darwin_x86_64.tar.gz"
      sha256 "a2075c74cc62288cb2ef59d0d89f335f554edfdce4cd43495066f8a08d76fd1d"

      def install
        bin.install "ncci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0/ncci_Linux_arm64.tar.gz"
      sha256 "8d608a96dd727e4a8f2cae3063e8101d5589ac6c01eaffc874f7b48aa0afa8e3"

      def install
        bin.install "ncci"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0/ncci_Linux_x86_64.tar.gz"
      sha256 "8fb6071c3bad2e10a3daf28352cadafddb7430e8c941e56dcfa5e0fced3cb2cd"

      def install
        bin.install "ncci"
      end
    end
  end

  test do
    system "#{bin}/ncci version"
  end
end
