# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncci < Formula
  desc "neetoCI 1.0 command line interface."
  homepage "https://neetoci.com"
  version "1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0/ncci_Darwin_arm64.tar.gz"
      sha256 "af919ef91066aa9092561a6d5c90bd11b6788537dfd4cd4cc6bcdaaa0447e18e"

      def install
        bin.install "ncci"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0/ncci_Darwin_x86_64.tar.gz"
      sha256 "9ac403526ccb9dcfea927a5b3f734303da3417cce13a318d1e9a96d6a3699857"

      def install
        bin.install "ncci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0/ncci_Linux_arm64.tar.gz"
      sha256 "6fc80d0be8300eb26da183a0356bbb6ad4c3b89c0bd360bc84c06868189b81a6"

      def install
        bin.install "ncci"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0/ncci_Linux_x86_64.tar.gz"
      sha256 "62be8044309080136458018ab5e71063a86fda04416e7a15f1bf2ed13756ca93"

      def install
        bin.install "ncci"
      end
    end
  end

  test do
    system "#{bin}/ncci version"
  end
end
