# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sem < Formula
  desc "neetoCI 1.0 command line interface."
  homepage "https://neetoci.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0.0/sem_Darwin_arm64.tar.gz"
      sha256 "001fe2063413832073a9f6844c9f63f7746d6844756babf04be0a3b78cad4bbd"

      def install
        bin.install "sem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0.0/sem_Darwin_x86_64.tar.gz"
      sha256 "9134d8a678dde51f8e3c7222eed3b759f0fb3d573ba5d6ddc1190efa9ad8b247"

      def install
        bin.install "sem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0.0/sem_Linux_arm64.tar.gz"
      sha256 "63b0e8e2eb06d45a85e1b0c37c755529c284ca34cf2bdbc20dceab318374244e"

      def install
        bin.install "sem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bigbinary/neeto-ci-cli/releases/download/v1.0.0/sem_Linux_x86_64.tar.gz"
      sha256 "cb200ef192da3d9eac5073a3fc183084b8a25da0ff3129b5478445c8eacbe0e7"

      def install
        bin.install "sem"
      end
    end
  end

  test do
    system "#{bin}/sem version"
  end
end
